package com.example.twogether.alarm.entity;

public enum AlarmTrigger {
    INVITED_WORKSPACE_COLLABORATOR,
    INVITED_BOARD_COLLABORATOR,
    REMOVED_WORKSPACE_COLLABORATOR,
    OUT_WORKSPACE_COLLABORATOR,
    ADDED_CARD_COLLABORATOR,
    CARD_COMMENT_CREATE_EVENT,
    CARD_EDITED_DUE_EVENT,
    CARD_EDITED_EVENT
}
